server:
  port: 7812

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 350
      maximumSize: 350
      maxQueueSize: -1
      queueSizeRejectionThreshold: 20
      allowMaximumSizeToDivergeFromCoreSize: true
      
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints: 
    web:
      base-path: /actuator
      exposure: 
        include: "*"
  health:
    defaults:
      enabled: true

logging:
  pattern:
    level: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
    console: "%p, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %X{mdc.sid} %m%n"
  level:
    org.springframework.web: INFO
    com.citibanamex.api.document.manager: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
     
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: false 
  datasource:
    url: jdbc:sqlserver://18.222.84.90:1433;databaseName=EBSDB
    username: sa
    password: Ap4che01
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 3
constants:
  api:
    uri:
      basePath: /api/private/v1/channels/bne
      specificPaths:
        search: /payments/accounts/payees/search
        topUsed: /payments/accounts/payees/top-used
        payeeDetails: /payments/accounts/payees
        retrievePaymentConfiguration: /payments/bill/configuration/retrieve
  swagger:
    basePackage: com.citibanamex.api
    title: mafch-d-bne-payee-group
    version: 1.0
    nameDeveloper: Eduardo Castillo Mendoza
    contactUrl: https://www.anzen.com.mx/
    emailDeveloper: ecastillo@anzen.com.mx
    descriptionApi: Payee Group
    label: swagger-ui.html
    resourceLocation: classpath:/META-INF/resources/
    webjars: /webjars/**
    webjarsLocation: classpath:/META-INF/resources/webjars/
  errorResolver:  
    errorCodes:
      badRequestException: BNEE-400
      unauthorizedException: BNEE-401
      noHandlerFoundException: BNEE-404
      httpRequestMethodNotSupportedException: BNEE-405
      httpMediaTypeNotAcceptableException: BNEE-406
      httpMediaTypeNotSupportedException: BNEE-415
      servletRequestBindingException: BNEE-424
      httpMessageNotReadableException: BNEE-430
      methodArgumentNotValidException: BNEE-431
      constraintViolationException: BNEE-432
      exception: BNEE-500
      microserviceClientException: BNEE-530
      hystrixRuntimeException: BNEE-532
      retryableException: BNEE-533
      noAvalibleLocatorsException: BNEE-535
      databaseMsClientException: BNEE-550
    messages:
      genericErrorDescription: Something went wrong! Further details may be available in logs.
      genericFailureDescription: See error description at the corresponding catalog.
      unauthorizedText: Not Authorized
      invalidRequest: Invalid Request
      commaSeparator: ", "
  legacyMessageskey:
    key1: C735 030 006 001
    keyRetrieve2: C735 030 006 002
    keyRetrieve3: C735 030 006 003
    keyRetrieve4: C735 030 006 004
    keyRetrieve5: C735 030 006 005
    keyNotFound: Error description not found
  messages:
    requestLogger: REQUEST  {}
    responseLogger: RESPONSE {}
    errorString: ERROR {}
    responseDatabase: database response {}
    paymentReferenceNameLabelSpanish: Línea de captura.
    paymentReferenceNameLabelEnglish: Capture line.
  business:  
    sidBill: -BILL 
    sidBillSecondAuthorization: -BILL-SECOND-AUTHORIZATION


legacyMessages:
  "[C735 030 006 001]":
    1:  Consulta de establecimientos no disponible.
    5:  Establishmnet query not available.
  "[C735 030 006 002]":
    1:  Pago de servicios no disponible.
    5:  Service payment not available.
  "[C735 030 006 003]":
    1:  Pago de servicio no disponible.
    5:  Service payment not available.
  "[C735 030 006 004]":
    1:  No existen referencias para el servicio seleccionado.
    5:  There are not references for the selected service.
  "[C735 030 006 005]":    
    1:  COP no catalogado.
    5:  COP not found.

gemfire:
  locator: db-memory[10334]
  properties:
    logLevel: DEBUG
    clusterSslEnabled:
    clusterSslProtocols:
    clusterSslRequireAuthentication:
    clusterSslKeystoreType:
    clusterSslCiphers:
    clusterSslKeystorePassword:
    clusterSslTruststorePassword:
    clusterSslKeystore:
    clusterSslTruststore:
    clusterSslCertLabel:
  certificate:
    path:
