package com.expample.web.droolsdos

import com.expample.web.droolsdos.model.Fare;
import com.expample.web.droolsdos.model.TaxiRide;


global com.expample.web.droolsdos.model.Fare rideFare;
dialect "mvel"
    
rule "Calculate Taxi Fare - Scenario 2"
	when
        taxiRideInstance: TaxiRide(isNightSurcharge == true && distanceInMile < 10);
    then
        rideFare.setNightSurcharge(2);
        rideFare.setRideFare(60);
end
